/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package local.test.serialization.thrift.java;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2017-11-01")
public class TestRecord implements org.apache.thrift.TBase<TestRecord, TestRecord._Fields>, java.io.Serializable, Cloneable, Comparable<TestRecord> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TestRecord");

  private static final org.apache.thrift.protocol.TField FOO_FIELD_DESC = new org.apache.thrift.protocol.TField("foo", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField BAR_FIELD_DESC = new org.apache.thrift.protocol.TField("bar", org.apache.thrift.protocol.TType.I64, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new TestRecordStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new TestRecordTupleSchemeFactory();

  public java.lang.String foo; // required
  public long bar; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    FOO((short)1, "foo"),
    BAR((short)2, "bar");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // FOO
          return FOO;
        case 2: // BAR
          return BAR;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __BAR_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.FOO, new org.apache.thrift.meta_data.FieldMetaData("foo", org.apache.thrift.TFieldRequirementType.DEFAULT,
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.BAR, new org.apache.thrift.meta_data.FieldMetaData("bar", org.apache.thrift.TFieldRequirementType.DEFAULT,
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TestRecord.class, metaDataMap);
  }

  public TestRecord() {
  }

  public TestRecord(
    java.lang.String foo,
    long bar)
  {
    this();
    this.foo = foo;
    this.bar = bar;
    setBarIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TestRecord(TestRecord other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetFoo()) {
      this.foo = other.foo;
    }
    this.bar = other.bar;
  }

  public TestRecord deepCopy() {
    return new TestRecord(this);
  }

  @Override
  public void clear() {
    this.foo = null;
    setBarIsSet(false);
    this.bar = 0;
  }

  public java.lang.String getFoo() {
    return this.foo;
  }

  public TestRecord setFoo(java.lang.String foo) {
    this.foo = foo;
    return this;
  }

  public void unsetFoo() {
    this.foo = null;
  }

  /** Returns true if field foo is set (has been assigned a value) and false otherwise */
  public boolean isSetFoo() {
    return this.foo != null;
  }

  public void setFooIsSet(boolean value) {
    if (!value) {
      this.foo = null;
    }
  }

  public long getBar() {
    return this.bar;
  }

  public TestRecord setBar(long bar) {
    this.bar = bar;
    setBarIsSet(true);
    return this;
  }

  public void unsetBar() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __BAR_ISSET_ID);
  }

  /** Returns true if field bar is set (has been assigned a value) and false otherwise */
  public boolean isSetBar() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __BAR_ISSET_ID);
  }

  public void setBarIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __BAR_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case FOO:
      if (value == null) {
        unsetFoo();
      } else {
        setFoo((java.lang.String)value);
      }
      break;

    case BAR:
      if (value == null) {
        unsetBar();
      } else {
        setBar((java.lang.Long)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case FOO:
      return getFoo();

    case BAR:
      return getBar();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case FOO:
      return isSetFoo();
    case BAR:
      return isSetBar();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof TestRecord)
      return this.equals((TestRecord)that);
    return false;
  }

  public boolean equals(TestRecord that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_foo = true && this.isSetFoo();
    boolean that_present_foo = true && that.isSetFoo();
    if (this_present_foo || that_present_foo) {
      if (!(this_present_foo && that_present_foo))
        return false;
      if (!this.foo.equals(that.foo))
        return false;
    }

    boolean this_present_bar = true;
    boolean that_present_bar = true;
    if (this_present_bar || that_present_bar) {
      if (!(this_present_bar && that_present_bar))
        return false;
      if (this.bar != that.bar)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetFoo()) ? 131071 : 524287);
    if (isSetFoo())
      hashCode = hashCode * 8191 + foo.hashCode();

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(bar);

    return hashCode;
  }

  @Override
  public int compareTo(TestRecord other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetFoo()).compareTo(other.isSetFoo());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFoo()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.foo, other.foo);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetBar()).compareTo(other.isSetBar());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBar()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.bar, other.bar);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("TestRecord(");
    boolean first = true;

    sb.append("foo:");
    if (this.foo == null) {
      sb.append("null");
    } else {
      sb.append(this.foo);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("bar:");
    sb.append(this.bar);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TestRecordStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TestRecordStandardScheme getScheme() {
      return new TestRecordStandardScheme();
    }
  }

  private static class TestRecordStandardScheme extends org.apache.thrift.scheme.StandardScheme<TestRecord> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TestRecord struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
          break;
        }
        switch (schemeField.id) {
          case 1: // FOO
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.foo = iprot.readString();
              struct.setFooIsSet(true);
            } else {
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // BAR
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.bar = iprot.readI64();
              struct.setBarIsSet(true);
            } else {
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TestRecord struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.foo != null) {
        oprot.writeFieldBegin(FOO_FIELD_DESC);
        oprot.writeString(struct.foo);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(BAR_FIELD_DESC);
      oprot.writeI64(struct.bar);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TestRecordTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TestRecordTupleScheme getScheme() {
      return new TestRecordTupleScheme();
    }
  }

  private static class TestRecordTupleScheme extends org.apache.thrift.scheme.TupleScheme<TestRecord> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TestRecord struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetFoo()) {
        optionals.set(0);
      }
      if (struct.isSetBar()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetFoo()) {
        oprot.writeString(struct.foo);
      }
      if (struct.isSetBar()) {
        oprot.writeI64(struct.bar);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TestRecord struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.foo = iprot.readString();
        struct.setFooIsSet(true);
      }
      if (incoming.get(1)) {
        struct.bar = iprot.readI64();
        struct.setBarIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

